### ISSUE TITLE
Iteration 1 - Submission QA Pass

### ISSUE THREAD

**Issue by klee721** [klee721/CS6920-Project-2#23]
AC:
* Do any last stage code cleanup/commenting as necessary
* Perform QA testing of currently functionality
* Perform QA testing on cloud-based DB functionality

**Comment by sofea1** [comment]
Issue identified: while the username must be unique, the first and last name must not be unique. This issue will be addressed in Iteration 2

**Comment by sivanathp** [comment]
I dont see any issues. All iteration 1 functionality is working

**Comment by klee721** [comment]
Iteration 1 - Satisfactory grade
