### ISSUE TITLE
Populate Study Group UI with favorited questions

### ISSUE THREAD

**Issue by klee721** [klee721/CS6920-Project-2#46]
AC:
* DataGridView populates with QuestionID and Description (etc)
* Grid is clickable and question displays in UI
* Clicking Remove drops the Question from the favorites table

**Comment by klee721** [comment]
Moving this to Iteration 3, blocked by creation of associated DB table

**Comment by sivanathp** [comment]
DB table is created

**Comment by klee721** [comment]
done
