### ISSUE TITLE
Add new column 'Explanation' to the Questions Table; Update User and Admin Interface; 

### ISSUE THREAD

**Issue by sofea1** [klee721/CS6920-Project-2#60]

**Comment by sivanathp** [comment]
New column explanation is added to table

**Comment by sivanathp** [comment]
Explanation is populated with the details from the excel sheet

**Comment by sofea1** [comment]
Explanation field is added to model, DAL methods, and Admin interface to view, add, update a question with explanation.

**Comment by klee721** [comment]
Quiz interface now displays explanations if available
