### ISSUE TITLE
Refine application visuals

### ISSUE THREAD

**Issue by klee721** [klee721/CS6920-Project-2#66]
Make it look pretty!

**Comment by sofea1** [comment]
commit bbf03531050fb7f47b5cfad63732dc33dbf4434c

**Comment by sofea1** [comment]
commit 3ae1d9e71431b3c0607180851e31fc8fe223a1c7

**Comment by sofea1** [comment]
commit 5e09c09b904a5b534deb26c1b053cc98c98be061

**Comment by sofea1** [comment]
commit b51f19e43324cc2741a43b06bc3723d36d48e222

**Comment by sofea1** [comment]
commit 095911027d9e3ad3ef39668e055482acc22042c2

**Comment by sofea1** [comment]
commit d41fe72699fe4c185cb8adf89c179a955b61bcc0

**Comment by sofea1** [comment]
commit d41fe72699fe4c185cb8adf89c179a955b61bcc0

**Comment by sofea1** [comment]
commit 5f43ac44cbd9ebc166ce0f9bee3f757a57588d74

**Comment by sofea1** [comment]
commit 62cb5d33b29376e8506a8c2709669d7bfa69b23d

**Comment by sofea1** [comment]
commit 4c10ec5bc0b6809b278261c6b978689e539340b3

**Comment by sofea1** [comment]
commit ad695241d431a38ffd110347d533b71a4c9650ea

**Comment by sofea1** [comment]
commit 2a1ef57e517c31d245fa3f69efbc14ef6baa7c58
