### ISSUE TITLE
Add Complete Quiz/Missed Question counts to end game routine

### ISSUE THREAD

**Issue by klee721** [klee721/CS6920-Project-2#68]
AC:
* When a player finishes a quiz, stats about the completed quiz are written to Games table

**Comment by klee721** [comment]
The UI outputs the stats, but currently no stats are being written to the Games table. That issue is in development by Sivanath

**Comment by sivanathp** [comment]
The EndQuiz procedure, DAL, controller methods and unit tests are created.

**Comment by klee721** [comment]
Using new EndQuiz routine and a running counter, correct stats now display on the end of quiz pop up
